name: Regression Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn run eslint explorer

    - name: Test
      run: yarn test
